spring:
  data:
    mongodb:
      database: database
      host: localhost
      port: 27017
      replica-set-name: rs0

mongodb:
  collections:
    events: accounts
    positions: subscriptions

logging:
  level:
    org.springframework.data.mongodb: DEBUG
